version: "3.8"

services:
  free5gc-upf:
    container_name: upf
    image: free5gc/upf:v3.4.5
    command: bash -c "./upf-iptables.sh && ./upf -c ./config/upfcfg.yaml"
    volumes:
      - ./free5gc/config/upfcfg.yaml:/free5gc/config/upfcfg.yaml
      - ./free5gc/config/upf-iptables.sh:/free5gc/upf-iptables.sh
    cap_add:
      - NET_ADMIN
    networks:
      privnet:
        ipv4_address: 10.100.100.2
        aliases:
          - upf.free5gc.org
    profiles:
      - free5gc

  db:
    container_name: mongodb
    image: mongo:3.6.8
    command: mongod --port 27017
    expose:
      - "27017"
    volumes:
      - dbdata:/data/db
    networks:
      privnet:
        ipv4_address: 10.100.100.20
        aliases:
          - db
    profiles:
      - free5gc

  free5gc-nrf:
    container_name: nrf
    image: free5gc/nrf:v3.4.5
    command: ./nrf -c ./config/nrfcfg.yaml
    expose:
      - "8000"
    volumes:
      - ./free5gc/config/nrfcfg.yaml:/free5gc/config/nrfcfg.yaml
      - ./free5gc/cert:/free5gc/cert
    environment:
      DB_URI: mongodb://db/free5gc
      GIN_MODE: release
    networks:
      privnet:
        ipv4_address: 10.100.100.25
        aliases:
          - nrf.free5gc.org
    depends_on:
      - db
    profiles:
      - free5gc

  free5gc-amf:
    container_name: amf
    image: free5gc/amf:v3.4.5
    command: ./amf -c ./config/amfcfg.yaml
    expose:
      - "8000"
    volumes:
      - ./free5gc/config/amfcfg.yaml:/free5gc/config/amfcfg.yaml
      - ./free5gc/cert:/free5gc/cert
    environment:
      GIN_MODE: release
    networks:
      privnet:
        ipv4_address: 10.100.100.16
        aliases:
          - amf.free5gc.org
    depends_on:
      - free5gc-nrf
    profiles:
      - free5gc

  free5gc-ausf:
    container_name: ausf
    image: free5gc/ausf:v3.4.5
    command: ./ausf -c ./config/ausfcfg.yaml
    expose:
      - "8000"
    volumes:
      - ./free5gc/config/ausfcfg.yaml:/free5gc/config/ausfcfg.yaml
      - ./free5gc/cert:/free5gc/cert
    environment:
      GIN_MODE: release
    networks:
      privnet:
        ipv4_address: 10.100.100.30
        aliases:
          - ausf.free5gc.org
    depends_on:
      - free5gc-nrf
    profiles:
      - free5gc

  free5gc-nssf:
    container_name: nssf
    image: free5gc/nssf:v3.4.5
    command: ./nssf -c ./config/nssfcfg.yaml
    expose:
      - "8000"
    volumes:
      - ./free5gc/config/nssfcfg.yaml:/free5gc/config/nssfcfg.yaml
      - ./free5gc/cert:/free5gc/cert
    environment:
      GIN_MODE: release
    networks:
      privnet:
        ipv4_address: 10.100.100.40
        aliases:
          - nssf.free5gc.org
    depends_on:
      - free5gc-nrf
    profiles:
      - free5gc

  free5gc-pcf:
    container_name: pcf
    image: free5gc/pcf:v3.4.5
    command: ./pcf -c ./config/pcfcfg.yaml
    expose:
      - "8000"
    volumes:
      - ./free5gc/config/pcfcfg.yaml:/free5gc/config/pcfcfg.yaml
      - ./free5gc/cert:/free5gc/cert
    environment:
      GIN_MODE: release
    networks:
      privnet:
        ipv4_address: 10.100.100.50
        aliases:
          - pcf.free5gc.org
    depends_on:
      - free5gc-nrf
    profiles:
      - free5gc

  free5gc-smf:
    container_name: smf
    image: free5gc/smf:v3.4.5
    command: ./smf -c ./config/smfcfg.yaml -u ./config/uerouting.yaml
    expose:
      - "8000"
    volumes:
      - ./free5gc/config/smfcfg.yaml:/free5gc/config/smfcfg.yaml
      - ./free5gc/config/uerouting.yaml:/free5gc/config/uerouting.yaml
      - ./free5gc/cert:/free5gc/cert
    environment:
      GIN_MODE: release
    networks:
      privnet:
        ipv4_address: 10.100.100.60
        aliases:
          - smf.free5gc.org
    depends_on:
      - free5gc-nrf
      - free5gc-upf
    profiles:
      - free5gc

  free5gc-udm:
    container_name: udm
    image: free5gc/udm:v3.4.5
    command: ./udm -c ./config/udmcfg.yaml
    expose:
      - "8000"
    volumes:
      - ./free5gc/config/udmcfg.yaml:/free5gc/config/udmcfg.yaml
      - ./free5gc/cert:/free5gc/cert
    environment:
      GIN_MODE: release
    networks:
      privnet:
        ipv4_address: 10.100.100.70
        aliases:
          - udm.free5gc.org
    depends_on:
      - db
      - free5gc-nrf
    profiles:
      - free5gc

  free5gc-udr:
    container_name: udr
    image: free5gc/udr:v3.4.5
    command: ./udr -c ./config/udrcfg.yaml
    expose:
      - "8000"
    volumes:
      - ./free5gc/config/udrcfg.yaml:/free5gc/config/udrcfg.yaml
      - ./free5gc/cert:/free5gc/cert
    environment:
      DB_URI: mongodb://db/free5gc
      GIN_MODE: release
    networks:
      privnet:
        ipv4_address: 10.100.100.80
        aliases:
          - udr.free5gc.org
    depends_on:
      - db
      - free5gc-nrf
    profiles:
      - free5gc

  free5gc-chf:
    container_name: chf
    image: free5gc/chf:v3.4.5
    command: ./chf -c ./config/chfcfg.yaml
    expose:
      - "8000"
    volumes:
      - ./free5gc/config/chfcfg.yaml:/free5gc/config/chfcfg.yaml
      - ./free5gc/cert:/free5gc/cert
    environment:
      DB_URI: mongodb://db/free5gc
      GIN_MODE: release
    networks:
      privnet:
        ipv4_address: 10.100.100.90
        aliases:
          - chf.free5gc.org
    depends_on:
      - db
      - free5gc-nrf
      - free5gc-webui
    profiles:
      - free5gc

  free5gc-nef:
    container_name: nef
    image: free5gc/nef:latest
    command: ./nef -c ./config/nefcfg.yaml
    expose:
      - "8000"
    volumes:
      - ./free5gc/config/nefcfg.yaml:/free5gc/config/nefcfg.yaml
      - ./free5gc/cert:/free5gc/cert
    environment:
      GIN_MODE: release
    networks:
      privnet:
        ipv4_address: 10.100.100.95
        aliases:
          - nef.free5gc.org
    depends_on:
      - db
      - free5gc-nrf
    profiles:
      - free5gc

  free5gc-webui:
    container_name: webui
    image: free5gc/webui:v3.4.5
    command: ./webui -c ./config/webuicfg.yaml
    expose:
      - "2121"
    volumes:
      - ./free5gc/config/webuicfg.yaml:/free5gc/config/webuicfg.yaml
    environment:
      - GIN_MODE=release
    networks:
      privnet:
        ipv4_address: 10.100.100.99
        aliases:
          - webui
    ports:
      - "5000:5000"
      - "2122:2122"
      - "2121:2121"
    depends_on:
      - db
      - free5gc-nrf
    profiles:
      - free5gc

  cn-tg:
    privileged: true
    container_name: "cn-tg"
    image: tariromukute/core-network-traffic-generator:latest
    expose:
      - 80/tcp
      - 8080/tcp
      - 8805/udp
    volumes:
      - /lib/modules:/lib/modules:ro
      - /usr/src:/usr/src:ro
      - /usr/include/linux:/usr/include/linux:ro
      - /sys/kernel/debug:/sys/kernel/debug:rw 
      - ./free5gc/config/free5gc-ue.yaml:/opt/CoreNetworkTrafficGenerator/config/ue.yaml
      - ./free5gc/config/free5gc-gnb.yaml:/opt/CoreNetworkTrafficGenerator/config/gnb.yaml
      - ./output/:/var/log/CoreNetworkTrafficGenerator/
    command: python3 run.py --statistics --sctp --folder=/var/log/CoreNetworkTrafficGenerator/free5gc
    networks:
      privnet:
        ipv4_address: 10.100.100.140
    profiles:
      - cn-tg

networks:
  privnet:
    ipam:
      driver: default
      config:
        - subnet: 10.100.100.0/24
    driver_opts:
      com.docker.network.bridge.name: br-free5gc

volumes:
  dbdata:
